albums:
  - name: Full Disclosure
    picture: full_disclosure.png
    release_date: November, 2013
    blurb: ""
    tracks:
      - title: Best Thing I Never Had
        soloist: Maya Gunaseharan
        opb: Beyonc√©
      - title: Battlefield
        soloist: Gwen Waichman
        opb: Jordin Sparks
      - title: Streetcorner Symphony
        soloist: Parker Moore
        opb: Rob Thomas
      - title: Breakeven
        soloist: Grace Epstein
        opb: The Script
      - title: Set Fire to the Rain
        soloist: Alex Griffen
        opb: Adele
      - title: Misery
        soloist: Thomas Shepherd
        opb: Maroon 5
      - title: Perfect
        soloist: Lacey Caroline
        opb: "P!nk"
  - name: Black Tie Optional
    picture: black-tie-optional-new.jpg
    release_date: "April, 2010"
    blurb: "After a three-year lull, The Class Notes is back with a hit album
      featuring an exquisite blend of traditional Class Notes staples as well
      as a selection of soulful and playful tunes."
    tracks:
      - title: No One
        soloist: Gwen Waichman
        opb: Alicia Keys
      - title: Someday
        soloist: Alex Hahn
        opb: No More Kings
      - title: Dancing in the Street
        soloist: Rachel Kleinman
        opb: Martha and the Vandellas
      - title: "Nothin' Ever Hurt Like You"
        soloist: Thomas Shepherd
        opb: James Morrison
      - title: Bottle It Up
        soloist: Grace Epstein
        opb: Sara Bareilles
      - title: "King On Me (80's Medley)"
        soloist: Alex Woogmaster, Steve Linderman, Eugene Chang
        opb: Go West, Tears for Fears, A-Ha
      - title: Lucky
        soloist: Thomas Shepherd, Lindsay McDonald
        opb: Jason Mraz, Colbie Calliat
      - title: Shine
        soloist: Emma Thanhauser
        opb: Laura Izibor
      - title: Hometown Glory
        soloist: Gwen Waichman
        opb: Adele
      - title: Whatcha Say
        soloist: Thomas Shepherd
        opb: Jason Derulo
      - title: Honey
        soloist: Natalie Pierro
        opb: The Hush Sound
      - title: Only You
        soloist: Jacob Chamoun, Cassie Greene
        opb: Yaz
#################################
# Alumni
#################################
alumni:
  #################################
  # 2013
  #################################
  -
    year: 2013
    name: Chris Donaldson
    picture: Chris.png
  -
    year: 2013
    name: Julian Ordman
    picture: Julian.png
  -
    year: 2013
    name: Emma Thanhauser
    picture: Emma.png
  -
    year: 2013
    name: Supriya Kumar
    picture: Supriya.JPG
  #################################
  # 2012
  #################################
  -
    year: 2012
    name: Ha Lim Lee
    picture: Halim.png
  -
    year: 2012
    name: Alexander Hahn
    picture: Hahn.png
  -
    year: 2012
    name: Lacey Steinel
    picture: Lacey.png
  -
    year: 2012
    name: Alex Martino
    picture: Martino.JPG
  -
    year: 2012
    name: Maya Gunaseharan
    picture: Maya.JPG
  -
    year: 2012
    name: Lindsay McDonald
    picture: Lindsay.JPG
  -
    year: 2012
    name: Thomas Shepherd
    picture: Thomas.JPG
  -
    year: 2012
    name: 'Liankun "Luke" Zhu'
    picture: Luke.png
  -
    year: 2012
    name: Mitchell Davis
    picture: Mitchell.JPG
  #################################
  # 2011
  #################################
  -
    year: 2011
    name: Grace Epstein
    picture: Grace.png
  -
    year: 2011
    name: Cassie Greene
    picture: Cassie.png
  -
    year: 2011
    name: Gwendolyn Waichman
    picture: Gwen.png
  -
    year: 2011
    name: Jacob Chamoun
    picture: Jacob.png
  #################################
  # 2010
  #################################
  -
    year: 2010
    name: Olga Desyatnik
    picture: olga.gif
  -
    year: 2010
    name: Rachel Kleinman
    picture: rachel.gif
  -
    year: 2010
    name: Steve Linderman
    picture: steve.gif
  #################################
  # 2009
  #################################
  -
    year: 2009
    name: Eugene Chang
    picture: Eugene.gif
  -
    year: 2009
    name: Scott Hayes
    picture: Scott.gif
  -
    year: 2009
    name: Natalie Pierro
    picture: Natalie.gif
  -
    year: 2009
    name: Alex Woogmaster
    picture: woog.gif
  #################################
  # 2008
  #################################
  -
    year: 2008
    name: Anderson Clark
    picture: anderson.gif
  -
    year: 2008
    name: Jill Lange
  -
    year: 2008
    name: Andrew Majak
  -
    year: 2008
    name: Natasha Major
  -
    year: 2008
    name: Amanda Soled
    picture: amanda.gif
  -
    year: 2008
    name: Phil Torres
    picture: phil.gif
  #################################
  # 2007
  #################################
  -
    year: 2007
    name: Nellie Thompson
    picture: nellie.gif
name: The Class Notes
tagline: Cornell University's Original Co-Ed A Cappella Group
email: classnotes@cornell.edu

emails:
  general: classnotes@cornell.edu
  gm: gm@theclassnotes.com
  md: md@theclassnotes.com
  pres: president@theclassnotes.com

links:
  general_email: "[classnotes@cornell.edu](mailto:classnotes@cornell.edu)"
  gm_email: "[gm@theclassnotes.com](mailto:gm@theclassnotes.com)"
  md_email: "[md@theclassnotes.com](mailto:md@theclassnotes.com)"
  pres_email: "[president@theclassnotes.com](mailto:president@theclassnotes.com)"

permalink: "/:year/:month/:day/:title/"
markdown: redcarpet
relative_permalinks: false

twitter:
  name: theclassnotes
  link: http://twitter.com/theclassnotes
facebook:
  name: theclassnotes
  link: http://facebook.com/theclassnotes
youtube:
  name: cornellclassnotes
  link: http://youtube.com/cornellclassnotes

exclude:
  - 'Guardfile'
  - 'Gemfile*'
  - '.gitignore'
  - 'Rakefile'
  - 'README.markdown'
#################################
# Current Notes
#################################

current_notes:
  ladies:
    -
      name: Catherine Rieflin '15
      picture: Catherine.JPG
      part: Soprano
      position: President
    -
      name: Jessica Li '15
      picture: Jessica.JPG
      part: Alto
      position:
    -
      name: Emily Woisin '15
      picture: Emily.jpg
      part: Alto
      position: General Manager
    -
      name: Alex Griffen '14
      picture: Alex.JPG
      part: Alto
      position:
  gentlemen:
    -
      name: Jeffrey Schwartz '14
      picture: Jeff.jpg
      part: Tenor
      position: Musical Director
    -
      name: Ethan Fuld '16
      picture: Ethan.jpg
      part: Tenor
      position: Treasurer
    -
      name: Joe Neumeyer '16
      picture: Joe.jpg
      part: Baritone
      position: Social Chair
    -
      name: Parker Moore '14
      picture: Parker.JPG
      part: Bass
      position:
    -
      name: Dan Rosenthal '15
      picture: Dan.jpg
      part: Bass
      position: Currently Abroad
prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published?"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
#################################
# Repertoire
#################################

current_repertoire:
-
  title: Sweet Nothing
  original_artist: Calvin Harris, Florence Welch
  soloist: "Catherine Rieflin '15"
  arranger:
-
  title: Let Me Love You
  original_artist: NeYo
  soloist: "Joe Neumeyer '16"
  arranger:
-
  title: Put the Gun Down
  original_artist: ZZ Ward
  soloist: "Emily Woisin '16"
  arranger:
-
  title: Gone, Gone, Gone
  original_artist: Phillip Phillips
  soloist: "Ethan Fuld '16"
  arranger:
-
  title: I Feel The Earth Move
  original_artist: Carole King
  soloist: "Emily Woisin '16"
  arranger: "Jeff Schwartz '13"
-
  title: Daylight
  original_artist: Marron 5
  soloist: "Jeff Schwartz '14"
  arranger: "Julian Ordman '13"

recently_retired_repertoire:
-
  title: Best Thing I Never Had
  original_artist: Beyonce
  soloist: "Maya Gunaseharan '12"
  arranger: "Julian Ordman '13"
-
  title: Blown Away
  original_artist: Carrie Underwood
  soloist: "Jessica Li '15"
  arranger: "Julian Ordman '13,<br>Alex Griffen '14"
-
  title: Chariot
  original_artist: Gavin DeGraw
  soloist: "Julian Ordman '13"
  arranger: "Julian Ordman '13"
-
  title: Fine By Me
  original_artist: Andy Grammer
  soloist: "Chris Donaldson '14"
  arranger: "Luke Zhu '12"
-
  title: Hold My Heart
  original_artist: Sara Bareilles
  soloist: "Emma Thanhauser '13"
  arranger: "Julian Ordman '13"
-
  title: Dark Side
  original_artist: Kelly Clarkson
  soloist: "Catherine Rieflin '15"
  arranger: "Julian Ordman '13"
-
  title: "I Won't Give Up"
  original_artist: Jason Mraz
  soloist: "Jeff Schwartz '14<br>(previously Chris Donaldson '14)"
  arranger: "Luke Zhu '12, Chris Donaldson '14"
-
  title: Many the Miles
  original_artist: Sara Bareilles
  soloist: "Emma Thanhauser '13"
  arranger: "Matt Bovenzi '06"
-
  title: Say (All I Need)
  original_artist: One Republic
  soloist: "Lindsay McDonald '12"
  arranger: "Julian Ordman '13"
-
  title: Set Fire to the Rain
  original_artist: Adele
  soloist: "Alex Griffen '12"
  arranger: "Julian Ordman '13"
-
  title: Torn
  original_artist: Natalie Imbruglia
  soloist: "Katie Rosenberger '16"
  arranger: "Michael Tang '06"
-
  title: "25 Miles"
  original_artist: Edwin Starr
  soloist: "Alex Martino '12"
  arranger: "Jacob Chamoun '11"
-
  title: Battlefield
  original_artist: Jordin Sparks
  soloist: "Gwen Waichman '11"
  arranger: "Lindsay McDonald '12"
-
  title: Breakeven
  original_artist: The Script
  soloist: "Grace Epstein '11"
  arranger: "Luke Zhu '12"
-
  title: "Don't Stop Believing"
  original_artist: Journey
  soloist: "Rachel Kleinman '10,<br>Thomas Shepherd '12"
  arranger: "Jacob Chamoun '11"
-
  title: Earth Song
  original_artist: Michael Jackson
  soloist: "Luke Zhu '12,<br>Lacey Steinel '12,<br>Alex Griffen '14,<br>Gwen Waichman '11"
  arranger: "Grace Epstein '11,<br>Luke Zhu '12"
-
  title: Easy
  original_artist: The Commodores
  soloist: "Luke Zhu '12"
  arranger: "Luke Zhu '12"
-
  title: Easy
  original_artist: Rascal Flatts ft. Natasha Bedingfield
  soloist: "Jeff Schwartz '14,<br>Emma Thanhauser '13"
  arranger: "Matt Bovenzi '06"
-
  title: "F**kin' Perfect"
  original_artist: "Pink"
  soloist: "Lacey Steinel '12"
  arranger: "Julian Ordman '13"
-
  title: Gunpowder and Lead
  original_artist: Miranda Lambert
  soloist: "Cassie Greene '11"
  arranger: "Julian Ordman '13"
-
  title: Happy Ending
  original_artist: Mika
  soloist: "Alex Hahn '12"
  arranger: "Cassie Greene '11"
-
  title: "Haven't Met You Yet"
  original_artist: Michael Buble
  soloist: "Julian Ordman '13"
  arranger: "Jacob Chamoun '11"
-
  title: Misery
  original_artist: Maroon 5
  soloist: "Thomas Shepherd '12"
  arranger: "Julian Ordman '13"
-
  title: Parachute
  original_artist: Ingrid Michaelson
  soloist: "Emma Thanhauser '13"
  arranger: "Grace Epstein '11"
-
  title: Something To Believe In
  original_artist: Parachute
  soloist: "Alex Martino '12"
  arranger: "Parker Moore '14"
-
  title: Streetcorner Symphony
  original_artist: Rob Thomas
  soloist: "Parker Moore '14"
  arranger: "Luke Zhu '12"
-
  title: Water and a Flame
  original_artist: Ingrid Michaelson
  soloist: "Alex Hahn '12,<br>Gwen Waichman '11"
  arranger: "Luke Zhu '12"
